apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  selector:
    matchLabels:
      app: flask
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: {{ .Values.image.repository  }}
        ports:
          - containerPort: 8080   
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080
    name: http
  type: {{ .Values.service.type }}  
  selector:
    app: flask